@startuml

actor HR as "HR Advisor"
actor DM as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC as "Get salaries"
    usecase UC1 as "Get all salaries"
    usecase UC2 as "Get salaries in a department"
    usecase UC3 as "Get salaries in a department"
    usecase UC4 as "Get salaries by role"
    usecase UC5 as "Add new employees"
    usecase UC6 as "View employee's details"
    usecase UC7 as "Update employee's details"
    usecase UC8 as "Delete employee's details"

    usecase UCa as "Produce report"

    UC ..> UC1 : include
    UC ..> UC2 : include
    DM - UC3
    UC ..> UC4 : include
    UC ..> UC5 : include
    UC ..> UC6 : include
    UC ..> UC7 : include
    UC ..> UC8 : include

    UC1 ..> UCa : include
    UC2 ..> UCa : include
    UC3 ..> UCa : include
    UC4 ..> UCa : include

    HR - UC
    UC3 - Database
    HR - UC5
    HR - UC6
    HR - UC7
    HR - UC8
    UC4 ..> UCa : include
    UC - Database
}

@enduml